version: '3'

services:

  laravel:
    build:
      context: .docker/laravel
    container_name: laravel_ticket
    volumes:
      - .:/var/www/html
    networks:
      -   ticket-network

  nginx:
    build:
      context: .docker/nginx
    container_name: nginx_ticket
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      -   ticket-network

  db:
    image: mysql:8
    #command: --innodb-use-native-aio=0
    container_name: db_ticket
    tty: true
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ticket
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      -   ticket-network

networks:
  ticket-network:
    driver: bridge
